# Generated by Django 4.2.21 on 2025-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tipo_documento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
