# Generated by Django 4.2.21 on 2025-06-12 06:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0002_payment_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('fechacreacion', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=25)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('idcontador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('nombreDescuento', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descuento', models.IntegerField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('precio_convertido', models.IntegerField()),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('alerta', models.BooleanField()),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('idadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateField()),
                ('estado', models.BooleanField()),
                ('idvendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.JSONField()),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('tipo_entrega', models.CharField(max_length=9)),
                ('direccion_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_estimada', models.DateField()),
                ('idPagoAPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.payment')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
                ('idvendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPagoAPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pagos.payment')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha_envio', models.DateField()),
                ('leido', models.BooleanField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idinforme', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('idcontador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.contador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idventaprod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.inventario')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('idcarritoprod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idcarrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.carritocompra')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='idcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
        ),
    ]
