# Generated by Django 5.0.7 on 2025-05-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=25)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('idcontador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=25)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('alerta', models.BooleanField()),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idinforme', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('idcontador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.contador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('idcarritoprod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idcarrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.carritocompra')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha_envio', models.DateField()),
                ('leido', models.BooleanField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('idvendedor', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('tipo_entrega', models.CharField(max_length=9)),
                ('direccion_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_estimada', models.DateField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('zona', models.CharField(max_length=20)),
                ('idadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.administrador')),
            ],
        ),
    ]
