# Generated by Django 4.2.21 on 2025-06-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.sucursal'),
            preserve_default=False,
        ),
    ]
