# Generated by Django 4.2.21 on 2025-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDescuento', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=25)),
                ('descuento', models.IntegerField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
