# Generated by Django 4.2.21 on 2025-06-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_vendedor_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='idvendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vendedor'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='idcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
        ),
    ]
