# Generated by Django 5.0.7 on 2025-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_administrador_cliente_contador_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
