# Generated by Django 4.2.21 on 2025-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='id',
        ),
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
