# Generated by Django 4.2.21 on 2025-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_notificacion_idvendedor_alter_notificacion_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
