# Generated by Django 5.0.7 on 2025-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_inventario_imagen_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
