# Generated by Django 4.2.21 on 2025-05-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_remove_descuento_id_alter_descuento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateField()),
                ('estado', models.BooleanField()),
                ('idvendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idventaprod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.inventario')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.venta')),
            ],
        ),
    ]
