# Generated by Django 4.2.21 on 2025-06-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_pedido_notificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('idbodeguero', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('idadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.administrador')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='notificacion',
            name='idbodeguero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.bodeguero'),
        ),
    ]
