# Generated by Django 5.0.7 on 2025-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_inventario_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
