# Generated by Django 4.2.21 on 2025-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(default='Helen', max_length=25),
            preserve_default=False,
        ),
    ]
