# Generated by Django 4.2.21 on 2025-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_bodeguero_notificacion_idbodeguero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificado_cliente',
            field=models.BooleanField(default=0),
        ),
    ]
