# Generated by Django 5.0.7 on 2025-05-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '__first__'),
        ('principal', '0005_carritocompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPagoAPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pagos.payment')),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
    ]
