# Generated by Django 5.0.7 on 2025-05-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='rut',
        ),
        migrations.AddField(
            model_name='pago',
            name='idcliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
            preserve_default=False,
        ),
    ]
