# Generated by Django 4.2.21 on 2025-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_pago_rut_pago_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio_convertido',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
